### ISSUE TITLE
Wildcard support for deleting all artifacts

### ISSUE THREAD

**Issue by benstear** [GeekyEggo/delete-artifact#1]
Is there a way to delete all artifacts, regardless of their name(s)? The names of my artifacts vary, so this would be a nice feature :)

**Comment by GeekyEggo** [comment]
Great suggestion; I think adding wildcard support would be a great addition. I've got some free time this weekend so I'll see what I can do and keep you posted.

**Comment by benstear** [comment]
Awesome, thanks!

**Comment by LewisGaul** [comment]
+1 for this, would imagine you'd want to use [@actions/glob](https://github.com/actions/toolkit/tree/master/packages/glob) as mentioned by [@actions/upload-artifact](https://github.com/actions/upload-artifact)?

**Comment by benstear** [comment]
Yes, that would be perfect! My CI workflow generates artifacts named by according to which previous jobs have passed,. I need them for the next job, but I'd like to delete them all at the end of the workflow. The wildcard feature would make this super easy.
________________________________

**Comment by GeekyEggo** [comment]
@LewisGaul I agree, using [@actions/glob](https://github.com/actions/toolkit/tree/master/packages/glob) would be optimal; it appears that [`Pattern`](https://github.com/actions/toolkit/blob/master/packages/glob/src/internal-pattern.ts) is only provided as an internal. Do you know of an example whereby the glob is being used as a pattern match, instead of file discovery?

**Comment by LewisGaul** [comment]
@GeekyEggo Hmm good point. I'm not very familiar with the setup with implementing github actions or with javascript/typescript, so not clear where an API for general glob pattern matching should be exposed from - seems reasonable that an API should perhaps be added to `actions/glob`?

A simpler alternative that would be just as good for me (and it sounds like it would for the OP too) would be to delete all artifacts for the workflow in the case that no `name` field was given. This wouldn't preclude from adding glob matching later on if desired. Thoughts?

**Comment by GeekyEggo** [comment]
@benstear and @LewisGaul I've added support for glob pattern matching (utilising [`minimatch`](https://www.npmjs.com/package/minimatch)). It would be great if you could check if the changes fulfil your requirements by targeting the [1-glob-support](https://github.com/GeekyEggo/delete-artifact/tree/1-glob-support) branch via: `geekyeggo/delete-artifact@1-glob-support`

As the changes aren't breaking, and if you're happy with things, I'll update v1 this week.

**Comment by benstear** [comment]
@GeekyEggo  works great for me, thanks very much for implementing this.

**Comment by LewisGaul** [comment]
@GeekyEggo I've tested it - I tried a few variants and all worked, including `"*"` to delete all artefacts.
I did come across one apparent regression: for some reason when specifying a glob expression with `useGlob: false` I got no warning saying that it wasn't found (and no artefacts were deleted as expected). See my equivalent runs with [1-glob-support](https://github.com/LewisGaul/minegauler/actions/runs/159787268) compared to [v1](https://github.com/LewisGaul/minegauler/actions/runs/159792727).

**Comment by GeekyEggo** [comment]
@LewisGaul you're right; this was a change to how artifacts are matched against supplied `names`. Previously `names` were iterated, and instead now artifacts are. This was primarily to prevent any duplicate attempts to remove artifacts that matched multiple globs. In hindsight, I may need to separate out the logic further to ensure the warning is still present when `useGlob: false` is the case.

**Comment by LewisGaul** [comment]
Makes sense, would definitely be good to keep that warning though. Thanks for working on it!

**Comment by GeekyEggo** [comment]
@LewisGaul the warning should now be present when `useGlob: false` (or not specified) again.

**Comment by LewisGaul** [comment]
Yep works for me!

There's no warning if nothing is matched with `useGlob: true`, but that's kind of a separate case which I'm not too bothered about (seems quite possible you might use `"*"` to delete everything and not care if there actually was anything to delete).

**Comment by moandor-y** [comment]
Hi @GeekyEggo , any plans to release this feature in a stable version? Our project could use this feature so it'll be really helpful to have a release with it.

**Comment by jonsimantov** [comment]
> Hi @GeekyEggo , any plans to release this feature in a stable version? Our project could use this feature so it'll be really helpful to have a release with it.

Same question here - any plans to release this in a stable version?

**Comment by yonatanaftali** [comment]
@GeekyEggo any update about this? It will help us a lot! :)

**Comment by GeekyEggo** [comment]
Hi all, apologies this has taken me so long; glob support is now available as part of v2, and is on by default. 🙂
