### ISSUE TITLE
Allow deletion of artifacts from other workflow runs

### ISSUE THREAD

**Issue by ofek** [GeekyEggo/delete-artifact#13]
Specifically, I would like to remove temporary artifacts that are required for triggered workflows like the event file described here https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches

**Comment by GeekyEggo** [comment]
Hey @ofek, when deleting artifacts, an access token is required. This action currently acquires that token from an undocumented environment variable, `ACTIONS_RUNTIME_TOKEN`. Sadly, IIRC this token only provides access to artifacts for the current workflow run.

If `ACTIONS_RUNTIME_TOKEN` does provide access to other workflow runs, then this action could be updated to accept an optional `run-id`, and delete matching artifacts. If this is something you would be interested in investigating, I would be open to pull requests. 👍

However, if the token doesn’t provide access to other workflow runs, it would require the user to generate and specify an access token, which is currently outside the scope of this action.

Alternatively, here are some other approaches that could be taken;
1. Utilise [List workflow run artifacts](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-workflow-run-artifacts) and [Delete an artifact](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact) API endpoints.
2. Use a reduced [Retention period](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact) when uploading artifacts, e.g. `retention-days: 1`.

**Comment by ofek** [comment]
`retention-days: 1` works well, thanks!
