### ISSUE TITLE
Tip: `@actions/artifact` added methods to delete artifacts

### ISSUE THREAD

**Issue by muzimuzhi** [GeekyEggo/delete-artifact#19]
See
- doc https://github.com/actions/toolkit/tree/main/packages/artifact#delete-an-artifact
- PR https://github.com/actions/toolkit/pull/1626

It seems to me then implementation in current repo could be simplified, once `@actions/artifact` ships a new release.

**Comment by GeekyEggo** [comment]
This is really helpful, and may remove the need for the new token parameter. Thank you for bringing this to my attention!

**Comment by muzimuzhi** [comment]
`actions/artifact` has just released v2.1.1 which ships with the new method `artifact.deleteArtifact()`, see https://www.npmjs.com/package/@actions/artifact/v/2.1.1 and the [doc for new method](https://www.npmjs.com/package/@actions/artifact/v/2.1.1#delete-an-artifact).

Note that as I'm writing this there's no tag `@actions/artifact@2.1.1` in repo https://github.com/actions/toolkit yet, but the new version is indeed uploaded to npm hence useable to downstream actions, e.g., https://github.com/actions/download-artifact/commit/9ac5cad9e2799348da3b2da75c8fbfa73ab3011c.

_Update:_ I reported https://github.com/actions/toolkit/issues/1658.

**Comment by GeekyEggo** [comment]
This is now resolved with `geekyeggo/delete-artifact@v5` 🚀
