### ISSUE TITLE
Incorrect Disclaimer?

### ISSUE THREAD

**Issue by lobabob** [GeekyEggo/delete-artifact#2]
The disclaimer in your README states that this is using a preview version of GitHub's runtime API which is subject to change. I looked through the [GitHub API docs](https://docs.github.com/en/rest/reference/actions#delete-an-artifact) but I didn't see anything there about the API being a preview or being unstable.

Am I just looking in the wrong place, or is the disclaimer incorrect?

**Comment by GeekyEggo** [comment]
Hey @lobabob, good question!

The [public API for GitHub's Artifacts](https://developer.github.com/v3/actions/artifacts/) is capable of working with artifacts from previously completed workflow runs (this may have changed, but was the case at time of writing this action).

To enable us to read and delete artifacts from the current workflow run it's possible to utilise a preview API; thankfully the preview API URL is supplied as an environment variable to all actions.

[src/runtimeHttpClient.js#L14](https://github.com/GeekyEggo/delete-artifact/blob/master/src/runtimeHttpClient.js#L14)
