### ISSUE TITLE
Errored deletion does not fail by default

### ISSUE THREAD

**Issue by radeksimko** [GeekyEggo/delete-artifact#20]
The Readme mentions:

> By default, the action will fail when it was not possible to delete an artifact (with the exception of name mismatches).

This is not a behaviour we have recently observed:

https://github.com/hashicorp/terraform-ls/actions/runs/7531206486/job/20499481014#step:2:9

```
Run geekyeggo/delete-artifact@9d15d164b1dcd538ff1b1a2984bc2c0240986c3b
  with:
    name: provider-schema-data
    useGlob: true
    failOnError: true
  env:
    PKG_NAME: terraform-ls
Error: Error: Parameter token or opts.auth is required
```

<img width="609" alt="Screenshot 2024-01-19 at 10 24 44" src="https://github.com/GeekyEggo/delete-artifact/assets/287584/65ffc6bb-5df6-476d-a013-41ac8d4f9077">

Assuming the intentions match with the documentation then I'd assume this is a bug.

--- 

Here is a full workflow definition: https://github.com/hashicorp/terraform-ls/blob/623f35c5a3019aa8c8a19fe067266b90095dc02e/.github/workflows/build.yml#L169-L175

I ran into this recently in https://github.com/hashicorp/terraform-ls/pull/1580 when I did not realise that the new v4 version requires some additional permissions and I realised later it failed silently.

**Comment by GeekyEggo** [comment]
This has been fixed in `v4.1.0`, for more information, please see https://github.com/GeekyEggo/delete-artifact/issues/21#issuecomment-1902730442 🥳
