### ISSUE TITLE
Default token is not read automatically

### ISSUE THREAD

**Issue by radeksimko** [GeekyEggo/delete-artifact#21]
The Readme says

> Support for actions/upload-artifact@v4 utilizes the GitHub REST API, and requires a permissive [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) ...

I'm assuming from `GITHUB_TOKEN` (environment variable) and from the current implementation that the token should be read automatically.

The most likely reason it is not however, is that the token is _both_ required and has `default` set:

https://github.com/GeekyEggo/delete-artifact/blob/3f83cd6bfd1bb806746002ab8b59cc6f76f1740f/action.yml#L9-L10

I ran into this recently in https://github.com/hashicorp/terraform-ls/pull/1582

Even after adding the following to the workflow

```yml
permissions:
  actions: write
```
I was still getting the following error:

```
Error: Error: Parameter token or opts.auth is required
```
(which also happened to be ignored due to https://github.com/GeekyEggo/delete-artifact/issues/20)

https://github.com/hashicorp/terraform-ls/actions/runs/7531206486/job/20499481014#step:2:9

**Comment by GeekyEggo** [comment]
Hi @radeksimko, I notice that the workflow referenced is referring to the `v4.0.0` commit directly, however the default value for `token` was introduced in `v4.1.0`. As `v4.0.0` handled missing tokens badly [read: it erroneously failed quietly], I would highly recommend updating the workflow to reference one of the following:
1. `@v4`
2. `@v4.1.0`
3. [`@65041433121f7239077fa20be14c0690f70569de`](https://github.com/GeekyEggo/delete-artifact/tree/65041433121f7239077fa20be14c0690f70569de)

**Comment by vojtapolasek** [comment]
Hello, I am also experiencing problems with the token, see this PR:
https://github.com/ComplianceAsCode/content/pull/11471
Do you have an idea what could be the problem? I added explicit token and I also added permissions.
But still I receive the error (see for example output of github action called "Automatus-cs8 run tests") that the action can't access the artifact.

**Comment by GeekyEggo** [comment]
The `token` parameter is no longer required as part of `geekyeggo/delete-artifact@v5` 🚀
