### ISSUE TITLE
"Resource not accessible by integration" in pull request

### ISSUE THREAD

**Issue by iTrooz** [GeekyEggo/delete-artifact#25]
It seems that this action fails with "Resource not accessible by integration" when trying to delete an artifact created in the same workflow in  a pull request context.

Do you know if there is a way to delete the artifact in this context ?

Example: https://github.com/WerWolv/ImHex/actions/runs/8344907183/job/22838673123?pr=1601#step:3:11

**Comment by GeekyEggo** [comment]
Hi @iTrooz, this might be fixed in the latest release; can you try with `v5` and let me know your findings please

**Comment by iTrooz** [comment]
It works indeed ! Thanks, and sorry I should have checked the latest release before
