### ISSUE TITLE
nodejs needs patch

### ISSUE THREAD

**Issue by abhishekpatelPM** [GeekyEggo/delete-artifact#8]
Warning given at the workflow:
"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: geekyeggo/delete-artifact"

**Comment by GeekyEggo** [comment]
Thanks for bringing this to my attention, @abhishekpatelPM. There have been pending changes that I've wanted to merge in, so have included this as part of them. This should be fixed in v2.
